### ISSUE TITLE
3.11.2版本在Ubuntu24.04中启动失败

### ISSUE THREAD

**Issue by unknown-o** [cnk3x/xunlei#139]
访问网页提示500错误，具体报错如下
![image](https://github.com/cnk3x/xunlei/assets/51825113/af49beb1-8291-4ff0-9598-d6a4c390b0f1)

**Comment by cnk3x** [comment]
你是在容器内以非root的用户启动的吧，目前有问题，还在尝试修复，非root用户启动没有权限删除/.dockerenv文件，你可以手动进入容器内删除根目录下的.dockerenv文件。

**Comment by unknown-o** [comment]
感谢回复！
但是容器根目录下并不存在此文件
![image](https://github.com/cnk3x/xunlei/assets/51825113/14716651-e36f-4bd8-8b16-70aae700fcf4)

**Comment by unknown-o** [comment]
操作步骤：
1.使用Ubuntu24.04安装纯净系统
2.使用get.docker.com安装最新版docker（使用清华源）
3.在用户主目录下创建docker-compose文件，并使用以下配置文件
```
services:
  xunlei:
    image: cnk3x/xunlei:latest
    restart: unless-stopped
    container_name: xunlei
    environment:
      - XL_DASHBOARD_PORT=8082      #网页访问的端口
      #- XL_DASHBOARD_HOST=0.0.0.0      #网页访问的地址
      - XL_DASHBOARD_USERNAME=admin  #网页访问的用户名
      - XL_DASHBOARD_PASSWORD=hidden  #网页访问的密码
      - XL_DIR_DOWNLOAD=/xunlei/downloads        #下载保存默认文件夹，默认 /xunlei/downloads
      - XL_DIR_DATA=/xunlei/data            #程序数据保存文件夹，默认 /xunlei/data
      - XL_LOG=null                 #日志文件输出目标，默认为 null, 可选 file, console
      - XL_LOGGER_MAXSIZE=1024      #日志文件最大大小
      - XL_LOGGER_COMPRESS=false     #是否压缩日志文件
    ports:
      - 8082:8082
    volumes:
      - ./config:/xunlei/data
      - ./downloads:/xunlei/downloads
 ```
创建完成后，当前所处目录为/home/ubuntu
用户为具有sudo权限的ubuntu用户
4.使用sudo docker compose up命令启动
最后打开网页地址，发现报错500
