### ISSUE TITLE
Docker HTTP ERROR 500

### ISSUE THREAD

**Issue by NirvanaCh** [cnk3x/xunlei#142]
docker compose
```yaml
services:
  xunlei:
    image: cnk3x/xunlei:latest
    container_name: xunlei
      #network_mode: host
    network_mode: bridge
    ports:
      - 2345:2345
    hostname: mynas
    privileged: true
      #environment:
      #- XL_DASHBOARD_HOST=***.***.***.***
      #- XL_DASHBOARD_PORT=2345
    volumes:
      - ./data:/xunlei/data
      - ./downloads:/xunlei/downloads
    restart: unless-stopped
```
bridge和host都试了。不加环境变量报500，加了报502，查看请求显示跨域。
docker logs尾部
```bash
xunlei  | time="05/16 18:53:01" level=info msg="  - HOME=/var/packages/pan-xunlei-com/shares/迅雷/.drive"
xunlei  | time="05/16 18:53:01" level=info msg="  - TLSInsecureSkipVerify=true"
xunlei  | time="05/16 18:53:01" level=info msg="xlp starting, listen at :2345"
```
端口未占用
