### ISSUE TITLE
容器启动了，但是无法访问网页，502

### ISSUE THREAD

**Issue by zhengshangjinx** [cnk3x/xunlei#148]
控制台日志如下（密码端口已脱敏）：

```
05/23 18:38:12 INF run mode=fork
05/23 18:38:12 INF proot init root=/xunlei
05/23 18:38:12 WRN bind src=/lib32 err="stat /lib32: no such file or directory"
05/23 18:38:12 WRN bind src=/libx32 err="stat /libx32: no such file or directory"
05/23 18:38:12 WRN bind src=/lib64 err="stat /lib64: no such file or directory"
05/23 18:38:12 INF fork root=/xunlei command=/usr/bin/xlp
05/23 18:38:12 INF fork pid=14
05/23 18:38:12 INF run mode=chroot
05/23 18:38:12 INF _  _ _  _ _  _ _    ____  _
05/23 18:38:12 INF  \/  |  | |\ | |    |___  |
05/23 18:38:12 INF _/\_ |__| | \| |___ |___  |
05/23 18:38:12 INF daemon version: v3.11.2-1
05/23 18:38:12 INF spk version: v3.11.2
05/23 18:38:12 INF
05/23 18:38:12 INF Config
05/23 18:38:12 INF   - DashboardPort:     9843
05/23 18:38:12 INF   - DashboardUsername: admin
05/23 18:38:12 INF   - DashboardPassword: GJHGJHGJ
05/23 18:38:12 INF   - DownloadPath:      /xunlei/downloads
05/23 18:38:12 INF   - DataPath:          /xunlei/data
05/23 18:38:12 INF   - Debug:             false
05/23 18:38:12 INF   - NewRoot:           /xunlei
05/23 18:38:12 INF Environ
05/23 18:38:12 INF   - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
05/23 18:38:12 INF   - HOSTNAME=a85c0dc2c15f
05/23 18:38:12 INF   - XL_UID=0
05/23 18:38:12 INF   - XL_GID=0
05/23 18:38:12 INF   - XL_DASHBOARD_PORT=9843
05/23 18:38:12 INF   - XL_DASHBOARD_USERNAME=admin
05/23 18:38:12 INF   - XL_DASHBOARD_PASSWORD=GJHGJHGJ
05/23 18:38:12 INF   - LANG=zh_CN.UTF-8
05/23 18:38:12 INF   - LANGUAGE=zh_CN.UTF-8
05/23 18:38:12 INF   - LC_ALL=C
05/23 18:38:12 INF   - XL_DEBUG=false
05/23 18:38:12 INF   - XL_CHROOT=/xunlei
05/23 18:38:12 INF   - HOME=/var/packages/pan-xunlei-com/shares/迅雷/.drive
05/23 18:38:12 INF   - XL_DIR_DOWNLOAD=/xunlei/downloads
05/23 18:38:12 INF   - XL_DIR_DATA=/xunlei/data
05/23 18:38:12 INF   - RUN_WITH_CHROOT=/xunlei
05/23 18:38:12 INF   - SYNOPLATFORM=rtd1296
05/23 18:38:12 INF   - SYNOPKG_PKGNAME=pan-xunlei-com
05/23 18:38:12 INF   - SYNOPKG_PKGVER=3.11.2
05/23 18:38:12 INF   - SYNOPKG_PKGDEST=/var/packages/pan-xunlei-com/target
05/23 18:38:12 INF   - SYNOPKG_DSM_VERSION_MAJOR=7
05/23 18:38:12 INF   - SYNOPKG_DSM_VERSION_MINOR=2
05/23 18:38:12 INF   - SYNOPKG_DSM_VERSION_BUILD=64570
05/23 18:38:12 INF   - DriveListen=unix:///var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock
05/23 18:38:12 INF   - PLATFORM=群晖
05/23 18:38:12 INF   - OS_VERSION=rtd1296 dsm 7.2-64570
05/23 18:38:12 INF   - ConfigPath=/var/packages/pan-xunlei-com/shares/迅雷/
05/23 18:38:12 INF   - DownloadPATH=/var/packages/pan-xunlei-com/shares/迅雷/下载
05/23 18:38:12 INF   - TLSInsecureSkipVerify=true
05/23 18:38:12 INF   - GIN_MODE=release
05/23 18:38:12 INF syno mock addr=:9843
05/23 18:38:12 INF xunlei-pan-cli-launcher.arm64 start cmd="/var/packages/pan-xunlei-com/target/bin/bin/xunlei-pan-cli-launcher.arm64 -launcher_listen unix:///var/packages/pan-xunlei-com/target/var/pan-xunlei-com-launcher.sock -pid /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid -logfile /var/packages/pan-xunlei-com/shares/迅雷/.drive/log-launcher.log -logsize 1MB"
05/23 18:38:12 INF xunlei-pan-cli-launcher.arm64 started pid=21
05/23 18:38:12 ERR [xunlei-pan-cli-launcher.arm64.2] loadHistory ReadFile err:open /var/packages/pan-xunlei-com/shares/迅雷/.drive/bin/.history: no such file or directory path:/var/packages/pan-xunlei-com/shares/迅雷/.drive/bin/.history
05/23 18:38:12 ERR [xunlei-pan-cli-launcher.arm64.2] KillDrivePid ioutil.ReadFile err:open /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid.child: no such file or directory
05/23 18:38:12 WRN [xunlei-pan-cli-launcher.arm64.2] kill process error:open /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid.child: no such file or directory
```

**Comment by zhengshangjinx** [comment]
docker-compose如下：

```
version: "3"
services:
  xunlei:
    image: cnk3x/xunlei:latest
    container_name: xunlei
    # 特权模式
    privileged: true
    # 环境变量
    environment:
      - XL_UID=0
      - XL_GID=0
      # 网页访问的端口
      - XL_DASHBOARD_PORT=9843
      # 网页访问的用户名
      - XL_DASHBOARD_USERNAME=admin
      # 网页访问的密码
      - XL_DASHBOARD_PASSWORD=这是密码
    # 挂载卷
    volumes:
      # 程序数据保存文件夹
      - /home/ubuntu/docker/xunlei/data:/xunlei/data
      # 下载保存默认文件夹
      - /home/ubuntu/docker/xunlei/downloads:/xunlei/downloads
    # 端口
    ports:
      # 服务访问端口
      - 2345:2345
    restart: unless-stopped
```
