### ISSUE TITLE
有同学反应内存占用过高

### ISSUE THREAD

**Issue by cnk3x** [cnk3x/xunlei#19]
加上限制参数即可

```
# compose.yml
services:
  xunlei:
    ......
    mem_limit: 512m
    cpus: 0.5
```
