### ISSUE TITLE
下载失败 （下载9102）

### ISSUE THREAD

**Issue by GanChangAn** [cnk3x/xunlei#197]
版本：3.21.0 
下载引擎：9.1207.160.28

不知道什么情况，所有的任务都无法下载。
错误提示，9102。
有谁能够下一步如何去做？谢谢。

**Comment by latel** [comment]
我也是

**Comment by JsonSong89** [comment]
很奇怪的日志
我的路径明明是
            - /mnt/m5/xunlei:/xunlei/m5
映射,为什么报错是 /m5 ?
但是下载时候又能识别我的目录的大小

```
moveDownloadSDKTmpFile ReadDir err:open /m5/zh-cn_windows_10_business_editions_version_22h2_updated_sep_2024_x64_dvd_1be03898.iso: no such file or directory btFilePath:/m5/zh-cn_windows_10_business_editions_version_22h2_updated_sep_2024_x64_dvd_1be03898.iso
10/24 12:42:04 WRN [xunlei-pan-cli] > DownloadRunner.runDownloadURL GetFirstDownloadPath err:empty download path

```

**Comment by latel** [comment]
我通过新增一个环境变量 UMASK=000，现在问题解决了

**Comment by JsonSong89** [comment]
我设置umask还是不行
加上 XL_UID  XL_GID 成功了,不确定是哪个生效
总之现在这个配置可以正常下载了
大家可以试试 

```yml
services:
    xunlei:
        privileged: true
        container_name: xunlei
        #https://github.com/cnk3x/xunlei
        environment:
          - TZ=Asia/Shanghai
          - XL_UID=65534
          - XL_GID=65534
          - XL_DEBUG=1
          - UMASK=000
          - XL_DASHBOARD_USERNAME=xxx
          - XL_DASHBOARD_PASSWORD=xxx
          - XL_DIR_DOWNLOAD=/xunlei/downloads:/xunlei/m5
        volumes:
            - ./data:/xunlei/data
            - /mnt/gc/xunlei:/xunlei/downloads
            - /mnt/m5/xunlei:/xunlei/m5
        ports:
            - 2345:2345
        image: cnk3x/xunlei:v3.20.2

```
