### ISSUE TITLE
[功能请求] 功能请求，获取基本信息的API

### ISSUE THREAD

**Issue by junyuyuan** [cnk3x/xunlei#198]
是否能够提供一个获取首页当前状态数据的API接口供我配置Homepage使用？
![image](https://github.com/user-attachments/assets/a99d5f37-e27b-48fd-908f-82acdecf0096)
下载中数量，下载速度之类的数据
```
            type: customapi
            url: API URL
            method: GET
            headers:
              X-API-TOKEN: Token
            mappings:
```
